stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

unit-test:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --no-cache make bash
  script:
    - make test
  rules:
    - when: always
