stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build_devind:
  stage: build
  image: alpine:latest
  before_script:
    - apk add --no-cache git make
  script:
    - make build
  artifacts:
    paths:
      - .build/

unit-test:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --no-cache make bash
  script:
    - make test
  rules:
    - when: always
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
